# Generated by Django 4.1.7 on 2023-02-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='detail',
            new_name='details',
        ),
    ]
